export const SET_TOKEN = "SET_TOKEN";
export const CLEAR_TOKEN = "CLEAR_TOKEN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const UPDATE_USER = "UPDATE_USER";
export const SET_DIRECT_ACCESS = "SET_DIRECT_ACCESS";
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const SET_LOADING_OVERLAY = "SET_LOADING_OVERLAY";
